# -*- coding: utf-8 -*-
"""ETS_STAT_MODEL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12knwpnsXew8pRxm5SDz7AtpaT68tmdSi

**ETS= Error / Trend / Seasonality Models **
"""

from google.colab import files
uploaded=files.upload()

import pandas as pd

df=pd.read_csv('airline-passengers.csv')
df

df.plot()

"""**After Seeing the Plotting Style , We came to Know that the trend of the data little bit higher than traditional y = mx (+c)**"""

df.info()

df.head(6)

from statsmodels.tsa.seasonal import seasonal_decompose

df1=pd.read_csv('airline-passengers.csv',index_col='Month',parse_dates=True)

df1

df1.info()

df1.plot()

"""We have to try to find the trend of the data increasing style
1. Additive Style
2. Multiplicative Style
"""

df1.head(4)

result=seasonal_decompose(df1['Passengers'],model='mul')
result.plot()

result=seasonal_decompose(df1['Passengers'],model='add')
result.plot()

"""**After Creation of Additive Model as well as multiplicative Model - We got Two Trend Based on Two Style , May Little bit difference in Trend - but using our normal vision we cannot see the changes because it is minor.**

**For This Dataset We Cannot Find any proper trend modeling style of the data ; but still we have two more options for practice**

1.   Rolling / Average Method
2.   Exponential Average Method
"""

df1.head(6)

df1.tail(6)

df1['6-Month-SMA']=df1['Passengers'].rolling(window=6).mean()
df1['12-Month-SMA']=df1['Passengers'].rolling(window=12).mean()
df1['240-Month-SMA']=df1['Passengers'].rolling(window=240).mean()
df1['480-Month-SMA']=df1['Passengers'].rolling(window=480).mean()
df1['600-Month-SMA']=df1['Passengers'].rolling(window=600).mean()

df1.plot()

"""**After performing Simple Moving Average of the Data , Unable to Find Our Desired Result ; So at Last trying to implement Exponential Concept Instead of Traditional Mean/Median/Avg etc.**"""

df2=pd.read_csv('airline-passengers.csv',index_col='Month',parse_dates=True)
df2

df1.head(14)

df['6-Month-SMA']=df['Passengers'].rolling(window=6).mean()
df['12-Month-SMA']=df['Passengers'].rolling(window=12).mean()
df['240-Month-SMA']=df['Passengers'].rolling(window=240).mean()
df['480-Month-SMA']=df['Passengers'].rolling(window=480).mean()
df['600-Month-SMA']=df['Passengers'].rolling(window=600).mean()

df.plot()

"""**Prediction & Forecasting**"""

df['EWMA12']=df['Passengers'].ewm(span=12,adjust=False).mean()
df['EWMA24']=df['Passengers'].ewm(span=24,adjust=False).mean()
df['EWMA120']=df['Passengers'].ewm(span=120,adjust=False).mean()
df['EWMA240']=df['Passengers'].ewm(span=240,adjust=False).mean()
df['EWMA480']=df['Passengers'].ewm(span=480,adjust=False).mean()
df['EWMA1200']=df['Passengers'].ewm(span=1200,adjust=False).mean()
df['EWMA2400']=df['Passengers'].ewm(span=2400,adjust=False).mean()
df['EWMA3600']=df['Passengers'].ewm(span=3600,adjust=False).mean()

df.plot()

df[['Passengers','EWMA240','EWMA1200','EWMA2400','EWMA3600']].plot()

